- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/client/fakes/softlayer_client_fake.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/client/softlayer_client.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/client/softlayer_client_test.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/data_types/softlayer_hardware.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softLayer_account.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softlayer_account_test.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softlayer_hardware.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softlayer_hardware_test.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/softlayer/client.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/softlayer/softlayer_account_service.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/softlayer/softlayer_hardware_service.go
Update the godeps file and _workspace code under Godeps folder to
leverage the latest merged hardware service code in softlayer-go project.
Signed-off-by: Tom Xing <xingzhou@cn.ibm.com>
> Update godeps to leverage the new hardware service in softlayer-go

- action/attach_disk.go
- action/concrete_factory.go
- action/concrete_factory_test.go
- action/detach_disk.go
- softlayer/vm/softlayer_creator.go
- softlayer/vm/softlayer_finder.go
- softlayer/vm/softlayer_vm.go
- softlayer/vm/softlayer_vm_test.go
- util/fakes/fake_ssh_client.go
- util/ssh_client.go
Move related ssh client and attach/detach disk code from softlayer-go project into CPI project
Signed-off-by: Edward Zhang <zhuadl@cn.ibm.com>
> Move ssh client and attach/detach disk code to CPI project

- softlayer/vm/softlayer_finder.go
- softlayer/vm/softlayer_finder_test.go
> faster VMFinder by using SLVG#GetObject

- .travis.yml
Seems to build past the go get vet step.
> trying new vet link

- integration/has_vm/has_vm_test.go
- integration/set_vm_metadata/set_vm_metadata_test.go
- test_helpers/integration_helpers_test.go
Made some changes mentioned in PR #36
> Tag verification set_vm_metadata_test

- softlayer/vm/interface.go
- softlayer/vm/softlayer_creator.go
- softlayer/vm/softlayer_creator_test.go
support more properties in create vm method , and according the max’s
suggestion , do some change code , and re-submit the change set.
> support more properties in create vm method

- .travis.yml
see if travis passes without gomega
> travis sudo and gomega changes

- softlayer/stemcell/softlayer_finder.go
Found this critical problem when trying to test OS Reload code, it's pretty urgent, since it broke create_vm function, I will try to write the integration test for it later soon, but please review and merge it ASAP. Already passed manual testing in real Softlayer environment. Thanks.
> Fixed a bug where to query stemcell with filter

- action/concrete_factory.go
- action/concrete_factory_test.go
- action/delete_stemcell.go
- action/delete_stemcell_test.go
- integration/create_stemcell/create_stemcell_test.go
- integration/delete_stemcell/delete_stemcell_test.go
> changed delete_stemcell to not delete VGBDTG

- action/create_disk.go
- action/create_disk_test.go
- action/create_stemcell.go
- action/create_stemcell_test.go
- action/create_vm.go
- action/create_vm_test.go
- integration/create_vm/create_vm_test.go
Dear Max, 
According the discuss in the mail , I had done the changes and had done some testing with the latest bosh-init code.
The result show that the changes can resolve the cid data type mismatch issue.
Thanks!
> fix cid data type issue to meet the cpi api spec

- action/networks.go
- action/networks_test.go
- softlayer/stemcell/softlayer_stemcell_test.go
- softlayer/vm/agent_env.go
- softlayer/vm/agent_env_for_vm_test.go
- softlayer/vm/agent_env_test.go
- softlayer/vm/network.go
- softlayer/vm/network_test.go
add network attribute "preconfigured" to support Softlayer network.
> add network attribute "preconfigured"

- integration/delete_vm/delete_vm_test.go
This commit depends on the addition in karafelix/softlayer-go@6427e30aeeb4b02a4e8895486b4edcd0cc40a1f0
> changed delete_vm_test to wait for no active transactions before deleting ssh key

- .gitignore
- integration/create_vm/create_vm_test.go
- softlayer/vm/interface.go
- softlayer/vm/softlayer_creator_test.go
- softlayer/vm/vm_utils.go
- test_fixtures/cpi_methods/create_vm.json
Ignore *.swp pattern
DCO 1.1 Signed-off-by: Alexey Miroshkin <alexey.miroshkin@ru.ibm.com>
> Ignore VIM swap files

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softlayer_network_storage.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softlayer_network_storage_test.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/softlayer/softlayer_network_storage_service.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/test_helpers/test_helpers.go
- action/create_vm.go
- action/create_vm_test.go
- action/delete_vm.go
- softlayer/common/softlayer_helper.go
- softlayer/vm/agent_env.go
- softlayer/vm/agent_env_for_vm_test.go
- softlayer/vm/agent_env_from_json_test.go
- softlayer/vm/agent_env_test.go
- softlayer/vm/agent_options.go
- softlayer/vm/interface.go
- softlayer/vm/network.go
- softlayer/vm/softlayer_creator.go
- softlayer/vm/softlayer_creator_test.go
- softlayer/vm/softlayer_vm.go
- softlayer/vm/softlayer_vm_test.go
- softlayer/vm/vm_utils.go
- test_fixtures/softlayer/SoftLayer_Virtual_Guest_Service_getLastTransaction_CloudInstanceUpgrade.json
Since all these changes are related with existing functions, we did not add additional functions,  all the existing unit test cases should cover these changes and changes are also included accordingly, you know, our unit test cases are only for interfaces  and syntax checking.
> Configure Network and some other chagnes

- integration/create_disk/create_disk_test.go
- integration/delete_disk/delete_disk_test.go
I noticed with create_disk I got an error on trying to delete the ssh key, so I added this to fix it, and I notice the same thing in delete_disk.
> Added wait before deleting ssh key

- softlayer/vm/softlayer_vm.go
- softlayer/vm/softlayer_vm_test.go
- test_fixtures/softlayer/SoftLayer_Virtual_Guest_Service_getActiveTransaction_ADEmpty.json
- test_fixtures/softlayer/SoftLayer_Virtual_Guest_Service_getActiveTransaction_ADInvalid.json
fix parsing float for averageDuration when the value is ""
if parsing float raises error, always set averageTransactionDuration to 0
> fix parsing float for averageDuration when the value is ""

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/client/softlayer_client.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/client/softlayer_client_test.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/data_types/softLayer_virtual_guest_block_device_template_group_init_parameters.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softLayer_virtual_guest_block_device_template_group.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softLayer_virtual_guest_block_device_template_group_test.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/softlayer/softlayer_virtual_guest_block_device_template_group.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/test_helpers/test_helpers.go
- action/delete_stemcell.go
- dev/set_vm_metadata.json
- integration/set_vm_metadata/set_vm_metadata_test.go
- softlayer/vm/fs_agent_env_service.go
- softlayer/vm/pool/vm_pool_manager.go
- softlayer/vm/softlayer_creator.go
- softlayer/vm/softlayer_vm.go
- softlayer/vm/softlayer_vm_test.go
- test_fixtures/cpi_methods/set_vm_metadata.json
- test_helpers/integration_helpers.go
- util/ssh_client.go
To address bug [109793518](https://www.pivotaltracker.com/story/show/109793518)
> Retrieve and set tags properly

- Godeps/_workspace/src/github.com/maximilien/softlayer-go/client/softlayer_client.go
> hide credentials in log

- integration/attach_disk/attach_disk_test.go
- integration/concurrency_sqlite/concurrency_sqlite_test.go
- integration/create_disk/create_disk_test.go
- integration/create_stemcell/create_stemcell_test.go
- integration/create_vm/create_vm_test.go
- integration/delete_disk/delete_disk_test.go
- integration/delete_vm/delete_vm_test.go
- integration/detach_disk/detach_disk_test.go
- integration/has_vm/has_vm_test.go
- integration/os_reload/os_reload_test.go
- integration/set_vm_metadata/set_vm_metadata_test.go
- softlayer/vm/softlayer_creator_test.go
Fixes #120.
Import reordering was done by go fmt.
> Remove code to set OS_RELOAD_ENABLED in tests

- softlayer/vm/fakes/fake_vm.go
- softlayer/vm/interface.go
- softlayer/vm/softlayer_hardware.go
- softlayer/vm/softlayer_hardware_creator.go
- softlayer/vm/softlayer_virtual_guest.go
- softlayer/vm/softlayer_virtual_guest_creator.go
bosh-softlayer-cpi should implement os_reload for baremetal
> os_reload for baremetal in bosh-softlayer-cpi

- action/create_vm.go
- api/dispatcher/json.go
- api/dispatcher/json_test.go
- softlayer/common/softlayer_helper.go
@maximilien "String" solution can't work. I got another idea, very simple, please review the code, I will add unit test if you agree with this solution. Thanks.
> Set true if localDiskFlag is not set

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/LICENSE
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/client/softlayer_client.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/client/softlayer_client_test.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softLayer_account.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softlayer_account_test.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softlayer_network_storage.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softlayer_network_storage_test.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softlayer_virtual_guest.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/services/softlayer_virtual_guest_test.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/softlayer/softlayer_account_service.go
- Godeps/_workspace/src/github.com/maximilien/softlayer-go/softlayer/softlayer_virtual_guest_service.go
@maximilien this PR is ready for review and merge, it's pretty urgent, since it's a prerequisite to other PRs. Thanks.
> Update Godeps from softlayer-go

- action/create_vm.go
- action/create_vm_test.go
- softlayer/common/softlayer_helper.go
- softlayer/vm/fs_agent_env_service.go
- softlayer/vm/fs_agent_env_service_test.go
@maximilien This PR is ready for review. Thanks.
> Print out warning msg if length of hostname >=64

- softlayer/vm/softlayer_virtual_guest_creator.go
- softlayer/vm/softlayer_virtual_guest_creator_test.go
Fix issue https://github.com/cloudfoundry/bosh-softlayer-cpi/issues/166
> fix issue 166

- softlayer/common/helper/softlayer_helper.go
- softlayer/vm/softlayer_virtual_guest.go
- vendor/github.com/maximilien/softlayer-go/services/softlayer_virtual_guest.go
- vendor/github.com/maximilien/softlayer-go/softlayer/softlayer_virtual_guest_service.go
- vendor/vendor.json
> Attaching disk fails if block devices < 3

- src/bosh-softlayer-cpi/action/has_disk.go
- src/bosh-softlayer-cpi/action/has_disk_test.go
Added action `has_disk` to check disk presence in SoftLayer, as described in [bosh.io](https://bosh.io/docs/cpi-api-v1.html#has-disk).
[#134980379] (https://www.pivotaltracker.com/story/show/134980379)
> Added action has_disk

- ci/tasks/setup-director.sh
Hi Dr.Max @maximilien,
Added one new property to yml template to run BATs. Thank you.
> added a new property to yml template

- config/dev.yml
`config/dev.yml` is in .gitignore and should not be part of the repository.
> Remove ignored file from bosh config directory

- ci/pipeline_v4.yml
- ci/tasks/promote-candidate.sh
Hi Dr.Max @maximilien ,
Just updated repository to master branch as ci code have been merged. Thanks.
> updated ci repository

- src/bosh-softlayer-cpi/softlayer/common/vm_utils.go
- src/bosh-softlayer-cpi/softlayer/common/vm_utils_test.go
For address [issue 210](https://github.com/cloudfoundry/bosh-softlayer-cpi-release/issues/210) and [tracker 140753119](https://www.pivotaltracker.com/n/projects/1344876/stories/140753119). 
@maximilien  It's ready for review. Thanks.
> Append DNS entry in /etc/hosts

- docs/README.md
- docs/mimimal-softlayer.yml
- docs/minimalistic_cf_deployment.md
We've used this updated cf template manifest and the updated README to do a successful deployment in Softlayer.
/cc @suhlig @smoser-ibm
> Update docs and template for CF deployment

- src/bosh-softlayer-cpi/action/create_vm.go
- src/bosh-softlayer-cpi/softlayer/common/interface.go
It's a minor change, we need to build an urgent release for Bluemix teams.
> Correct a typo and a worng name

- ci/pipeline_v4.yml
Update repo bosh and bosh-cpi-certification.
> update pipeline repo

- src/bosh-softlayer-cpi/softlayer/common/vm_utils.go
- src/bosh-softlayer-cpi/softlayer/common/vm_utils_test.go
- src/bosh-softlayer-cpi/softlayer/pool/softlayer_pool_creator.go
- src/bosh-softlayer-cpi/softlayer/vm/softlayer_virtual_guest_creator.go
- src/bosh-softlayer-cpi/softlayer/vm/softlayer_virtual_guest_creator_test.go
- src/bosh-softlayer-cpi/test_fixtures/softlayer/SoftLayer_Virtual_Guest_Service_createObject.json
- src/bosh-softlayer-cpi/test_fixtures/softlayer/SoftLayer_Virtual_Guest_Service_getObject.json
- src/bosh-softlayer-cpi/test_fixtures/softlayer/SoftLayer_Virtual_Guest_Service_getObjects.json
- src/bosh-softlayer-cpi/vendor/github.com/bluebosh/goodhosts/API.md
- src/bosh-softlayer-cpi/vendor/github.com/bluebosh/goodhosts/LICENSE
- src/bosh-softlayer-cpi/vendor/github.com/bluebosh/goodhosts/README.md
- src/bosh-softlayer-cpi/vendor/github.com/bluebosh/goodhosts/const.go
- src/bosh-softlayer-cpi/vendor/github.com/bluebosh/goodhosts/const_windows.go
- src/bosh-softlayer-cpi/vendor/github.com/bluebosh/goodhosts/goodhosts.go
- src/bosh-softlayer-cpi/vendor/github.com/bluebosh/goodhosts/utils.go
- src/bosh-softlayer-cpi/vendor/vendor.json
To address [tracker #145744835](https://www.pivotaltracker.com/story/show/145744835)
> #145744835 eliminate dup entry in hosts file

- src/bosh-softlayer-cpi/action/create_vm.go
- src/bosh-softlayer-cpi/action/create_vm_test.go
@maximilien There is a very urgent PR for review as soon as possible, the detailed info is in [#148050011](https://www.pivotaltracker.com/story/show/148050011), please help take a quick review when you get time. Thank you!
> #148050011 Set vcap password in env.bosh.password through CPI

- src/bosh-softlayer-cpi/vendor/github.com/maximilien/softlayer-go/data_types/softlayer_product_item_price.go
- src/bosh-softlayer-cpi/vendor/vendor.json
> [#149135787] Update softlayer-go vendor

- docs/deploy_dynamic_ip_director_with_bosh-deployment.md
@mattcui Please help to review.
Thank you~
> Add doc about deploy dynamic IP director

- .travis.yml
- src/bosh-softlayer-cpi/action/create_vm.go
- src/bosh-softlayer-cpi/integration/assertions.go
- src/bosh-softlayer-cpi/integration/dedicated_host_instance_test.go
- src/bosh-softlayer-cpi/integration/dedicated_instance_test.go
- src/bosh-softlayer-cpi/integration/integration_suite_test.go
- src/bosh-softlayer-cpi/integration/vm_test.go
- src/bosh-softlayer-cpi/softlayer/client/client.go
- src/bosh-softlayer-cpi/softlayer/client/fakes/fake_client.go
- src/bosh-softlayer-cpi/softlayer/client/instance_handler_test.go
- src/bosh-softlayer-cpi/softlayer/virtual_guest_service/fakes/fake_Instance_Service.go
- src/bosh-softlayer-cpi/softlayer/virtual_guest_service/instance_service.go
- src/bosh-softlayer-cpi/softlayer/virtual_guest_service/softlayer_virtual_guest_service_upgrade.go
- src/bosh-softlayer-cpi/softlayer/virtual_guest_service/softlayer_virtual_guest_service_upgrade_test.go
- src/bosh-softlayer-cpi/test_fixtures/services/SoftLayer_Product_Package_getItems.json
- src/bosh-softlayer-cpi/vendor/github.com/softlayer/softlayer-go/.gitignore
- src/bosh-softlayer-cpi/vendor/github.com/softlayer/softlayer-go/helpers/product/product.go
- src/bosh-softlayer-cpi/vendor/vendor.json
This PR worked on the upgrade for dedicated instances/dedicated host instances.
/cc @mattcui
> Refactor upgrade for dedicated host instances

- ci/bats/iaas/softlayer/prepare-bats-config.sh
- ci/bats/iaas/softlayer/prepare-bats-config.yml
- ci/bats/tasks/deploy-director-softlayer.sh
- ci/bats/tasks/deploy-director-softlayer.yml
- ci/bats/tasks/destroy-director.sh
- ci/pipeline.yml
- ci/pipeline_develop.yml
- ci/tasks/run-bats.sh
Hi @mattcui,
This PR fixed pipeline issue: cloudfoundry/bosh-softlayer-cpi-release#286
Please help to review. Thanks!
> Fix bats issue for director with dynamic network
